---
packages_to_install:
  - language-fish-shell
  - linter
  - linter-eslint
  - linter-stylelint
  - markdown-preview-plus
  - modular-snippets
  - sort-lines
  - atom-beautify
  - atom-live-server
  - export-html
  - open-in-browser
  - language-lua
