---
repositories_to_install:
  - homebrew/cask-versions # Repository for alternate app versions
  - homebrew/cask-fonts # Repository for binary font files
  - mongodb/brew # Repository needed to install mongodb
  # end_of_repositories

# Some binaries aren't listed here due they will be installed directly from
# other modules commands
binaries_to_install:
  - ansible
  - elm
  - ffmpeg
  - gist
  - hub
  - lua
  - mongodb-community
  - postgresql
  - pyenv
  - rename
  - rust
  - sqlite
  - tccutil
  - tree
  - unrar
  - youtube-dl
  # end_of_binaries

# Apps installed using Homebrew-cask. Some apps aren't listed here due they
# will be installed directly from its own module commands
apps_to_install:
  - 1password
  - abstract
  - adobe-acrobat-reader # 🤦‍
  - alfred
  - cyberduck
  - dash
  - docker
  - doxie
  - figma
  - firefox
  - flinto
  - google-chrome
  - iconjar
  - imageoptim
  - logitech-options
  - mactracker
  - microsoft-teams # 🤦‍
  - nextcloud
  - notion
  - onedrive # 🤦‍
  - qlcolorcode
  - qlmarkdown
  - qlstephen
  - sketch
  - skype-for-business # 🤦‍
  - slack
  - spotify
  - telegram
  - tor-browser
  - vlc
  - zeplin
  # end_of_casks


# From Homebrew-fonts
fonts_to_install:
  - font-chivo
  - font-crimson-pro
  - font-crimson-text
  - font-ibm-plex
  - font-inter
  - font-libre-baskerville
  - font-lora
  - font-roboto
  - font-spectral
  # end_of_casks
